CREATE TABLE FORNECEDORES (
	CODIGO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  	NOME VARCHAR(50)
);

CREATE TABLE CATEGORIAS (
	CODIGO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(50) 
);

CREATE TABLE PRODUTOS (
	CODIGO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 	DESCRICAO VARCHAR(100),
 	DATA_CADASTRO DATE,
  	VALOR_UNITARIO DOUBLE,
  	COD_CATEGORIA INT NOT NULL,
  	CONSTRAINT FK_PRODUTOS_CATEGORIAS FOREIGN KEY (COD_CATEGORIA)
  		REFERENCES CATEGORIAS (CODIGO)
);

CREATE TABLE PEDIDOS (
  	CODIGO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	QUANTIDADE INT NOT NULL,
 	VALOR_UNITARIO DOUBLE,
  	DATA DATE,
  	COD_FORNECEDORES INT NOT NULL,
  	COD_PRODUTOS INT NOT NULL,
  	CONSTRAINT FK_PEDIDOS_FORNECEDORES FOREIGN KEY (COD_FORNECEDORES)
  		REFERENCES FORNECEDORES (CODIGO)
  			on update CASCADE 
  			on delete RESTRICT,
  	CONSTRAINT FK_PEDIDOS_PRODUTOS FOREIGN KEY (COD_PRODUTOS) 
  		REFERENCES PRODUTOS (CODIGO)
    		on update CASCADE 
  			on delete RESTRICT
);


-- 3 - Faça um comando (FUC) para adicionar o campo data_ultima_compra na tabela fornecedor.
/*
CREATE TABLE
ALTER TABLE
DROP TABLE
*/
ALTER TABLE FORNECEDORES ADD COLUMN DATA_ULTIMA_COMPRA DATE;
ALTER TABLE FORNECEDORES DROP COLUMN data_ultima_compra;


-- 4- FUC para alterar o nome do atributo data em PEDIDOS para data_pedido.
ALTER TABLE PEDIDOS CHANGE COLUMN DATA DATA_PEDIDO DATE;

-- 5 - FUC para deletar o campo data_cadastro em produtos
alter table PRODUTOS drop column DATA_CADASTRO;

-- 6 -FUC para adicionar na relação categoria e produto para o delete ser em cascata e o update ser restrict.
ALTER TABLE PRODUTOS DROP CONSTRAINT FK_PRODUTOS_CATEGORIAS;

ALTER TABLE PRODUTOS
 	ADD CONSTRAINT FK_PRODUTOS_CATEGORIAS
    	FOREIGN KEY (COD_CATEGORIA)
    		REFERENCES CATEGORIAS(CODIGO)
            	ON DELETE CASCADE
                ON UPDATE RESTRICT;


-- ------------------------------------------
# 7 - FUC para aumentar o tamanho do domínio do campo nome do fornecedor para mais 30 caracteres.
ALTER TABLE FORNECEDORES
  MODIFY NOME VARCHAR(80) NOT NULL;
    
# 8 - FUC para apagar a tabela fornecedor. Explique o que vai acontecer com o seu esquema e as consequências disso.
DROP TABLE FORNECEDORES;

# 9 - Adicionar numero do pedido
ALTER TABLE PEDIDOS
  ADD COLUMN NUMERO_PEDIDO VARCHAR(255) NOT NULL;
  
  